# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10-slim-2022-11-25

FROM python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1
WORKDIR /backend

# install dependencies (rye)
COPY ./requirements.lock .
RUN sed '/-e/d' requirements.lock > requirements.txt && \
    pip install -r requirements.txt

ENV PYTHONPATH=/code
EXPOSE 8081