from datetime import datetime

import aiohttp
from cachetools import TTLCache, cached
from fastapi import HTTPException
from pydantic import BaseModel
from pydantic_core import Url

from app.env import env

RESOURCE = [
    {
        "url": "https://api.github.com/repos/iot49/leaf/releases/156320902",
        "assets_url": "https://api.github.com/repos/iot49/leaf/releases/156320902/assets",
        "upload_url": "https://uploads.github.com/repos/iot49/leaf/releases/156320902/assets{?name,label}",
        "html_url": "https://github.com/iot49/leaf/releases/tag/v0.0.8",
        "id": 156320902,
        "author": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": False,
        },
        "node_id": "RE_kwDOL4ZmU84JUUSG",
        "tag_name": "v0.0.8",
        "target_commitish": "main",
        "name": "Vv0.0.8",
        "draft": False,
        "prerelease": False,
        "created_at": "2024-05-17T18:48:52Z",
        "published_at": "2024-05-17T18:52:19Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168563915",
                "id": 168563915,
                "node_id": "RA_kwDOL4ZmU84KDBTL",
                "name": "ESP32_S3_N16R8-firmware.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1787424,
                "download_count": 0,
                "created_at": "2024-05-17T18:52:18Z",
                "updated_at": "2024-05-17T18:52:18Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.8/ESP32_S3_N16R8-firmware.bin",
            },
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168563914",
                "id": 168563914,
                "node_id": "RA_kwDOL4ZmU84KDBTK",
                "name": "ESP32_S3_N16R8-micropython.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1721888,
                "download_count": 0,
                "created_at": "2024-05-17T18:52:18Z",
                "updated_at": "2024-05-17T18:52:18Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.8/ESP32_S3_N16R8-micropython.bin",
            },
        ],
        "tarball_url": "https://api.github.com/repos/iot49/leaf/tarball/v0.0.8",
        "zipball_url": "https://api.github.com/repos/iot49/leaf/zipball/v0.0.8",
        "body": None,
    },
    {
        "url": "https://api.github.com/repos/iot49/leaf/releases/156315748",
        "assets_url": "https://api.github.com/repos/iot49/leaf/releases/156315748/assets",
        "upload_url": "https://uploads.github.com/repos/iot49/leaf/releases/156315748/assets{?name,label}",
        "html_url": "https://github.com/iot49/leaf/releases/tag/v0.0.4",
        "id": 156315748,
        "author": {
            "login": "iot49",
            "id": 80709989,
            "node_id": "MDQ6VXNlcjgwNzA5OTg5",
            "avatar_url": "https://avatars.githubusercontent.com/u/80709989?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iot49",
            "html_url": "https://github.com/iot49",
            "followers_url": "https://api.github.com/users/iot49/followers",
            "following_url": "https://api.github.com/users/iot49/following{/other_user}",
            "gists_url": "https://api.github.com/users/iot49/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iot49/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iot49/subscriptions",
            "organizations_url": "https://api.github.com/users/iot49/orgs",
            "repos_url": "https://api.github.com/users/iot49/repos",
            "events_url": "https://api.github.com/users/iot49/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iot49/received_events",
            "type": "User",
            "site_admin": False,
        },
        "node_id": "RE_kwDOL4ZmU84JUTBk",
        "tag_name": "v0.0.4",
        "target_commitish": "main",
        "name": "v0.0.4",
        "draft": False,
        "prerelease": False,
        "created_at": "2024-05-17T17:56:10Z",
        "published_at": "2024-05-17T18:09:33Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168557447",
                "id": 168557447,
                "node_id": "RA_kwDOL4ZmU84KC_uH",
                "name": "firmware.bin",
                "label": "",
                "uploader": {
                    "login": "iot49",
                    "id": 80709989,
                    "node_id": "MDQ6VXNlcjgwNzA5OTg5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/80709989?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/iot49",
                    "html_url": "https://github.com/iot49",
                    "followers_url": "https://api.github.com/users/iot49/followers",
                    "following_url": "https://api.github.com/users/iot49/following{/other_user}",
                    "gists_url": "https://api.github.com/users/iot49/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/iot49/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/iot49/subscriptions",
                    "organizations_url": "https://api.github.com/users/iot49/orgs",
                    "repos_url": "https://api.github.com/users/iot49/repos",
                    "events_url": "https://api.github.com/users/iot49/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/iot49/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1787504,
                "download_count": 0,
                "created_at": "2024-05-17T18:09:29Z",
                "updated_at": "2024-05-17T18:09:33Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.4/firmware.bin",
            },
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168557448",
                "id": 168557448,
                "node_id": "RA_kwDOL4ZmU84KC_uI",
                "name": "micropython.bin",
                "label": "",
                "uploader": {
                    "login": "iot49",
                    "id": 80709989,
                    "node_id": "MDQ6VXNlcjgwNzA5OTg5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/80709989?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/iot49",
                    "html_url": "https://github.com/iot49",
                    "followers_url": "https://api.github.com/users/iot49/followers",
                    "following_url": "https://api.github.com/users/iot49/following{/other_user}",
                    "gists_url": "https://api.github.com/users/iot49/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/iot49/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/iot49/subscriptions",
                    "organizations_url": "https://api.github.com/users/iot49/orgs",
                    "repos_url": "https://api.github.com/users/iot49/repos",
                    "events_url": "https://api.github.com/users/iot49/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/iot49/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1721968,
                "download_count": 0,
                "created_at": "2024-05-17T18:09:29Z",
                "updated_at": "2024-05-17T18:09:33Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.4/micropython.bin",
            },
        ],
        "tarball_url": "https://api.github.com/repos/iot49/leaf/tarball/v0.0.4",
        "zipball_url": "https://api.github.com/repos/iot49/leaf/zipball/v0.0.4",
        "body": "**Full Changelog**: https://github.com/iot49/leaf/compare/v0.0.3...v0.0.4\n",
    },
    {
        "url": "https://api.github.com/repos/iot49/leaf/releases/156307093",
        "assets_url": "https://api.github.com/repos/iot49/leaf/releases/156307093/assets",
        "upload_url": "https://uploads.github.com/repos/iot49/leaf/releases/156307093/assets{?name,label}",
        "html_url": "https://github.com/iot49/leaf/releases/tag/v0.0.2",
        "id": 156307093,
        "author": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": False,
        },
        "node_id": "RE_kwDOL4ZmU84JUQ6V",
        "tag_name": "v0.0.2",
        "target_commitish": "main",
        "name": "ESP32_S3_N16R8 V0.0.2",
        "draft": False,
        "prerelease": False,
        "created_at": "2024-05-17T16:56:26Z",
        "published_at": "2024-05-17T17:02:32Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168546849",
                "id": 168546849,
                "node_id": "RA_kwDOL4ZmU84KC9Ih",
                "name": "firmware.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1787424,
                "download_count": 0,
                "created_at": "2024-05-17T17:02:27Z",
                "updated_at": "2024-05-17T17:02:31Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.2/firmware.bin",
            },
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168546850",
                "id": 168546850,
                "node_id": "RA_kwDOL4ZmU84KC9Ii",
                "name": "micropython.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1721888,
                "download_count": 0,
                "created_at": "2024-05-17T17:02:27Z",
                "updated_at": "2024-05-17T17:02:31Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.2/micropython.bin",
            },
        ],
        "tarball_url": "https://api.github.com/repos/iot49/leaf/tarball/v0.0.2",
        "zipball_url": "https://api.github.com/repos/iot49/leaf/zipball/v0.0.2",
        "body": None,
    },
    {
        "url": "https://api.github.com/repos/iot49/leaf/releases/156151879",
        "assets_url": "https://api.github.com/repos/iot49/leaf/releases/156151879/assets",
        "upload_url": "https://uploads.github.com/repos/iot49/leaf/releases/156151879/assets{?name,label}",
        "html_url": "https://github.com/iot49/leaf/releases/tag/v0.0.1",
        "id": 156151879,
        "author": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": False,
        },
        "node_id": "RE_kwDOL4ZmU84JTrBH",
        "tag_name": "v0.0.1",
        "target_commitish": "main",
        "name": "leaf MicroPython VM for ESP32_S3_N16R8 0.0.1",
        "draft": False,
        "prerelease": False,
        "created_at": "2024-05-16T19:26:19Z",
        "published_at": "2024-05-16T19:30:27Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168357554",
                "id": 168357554,
                "node_id": "RA_kwDOL4ZmU84KCO6y",
                "name": "firmware.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1787344,
                "download_count": 3,
                "created_at": "2024-05-16T19:30:26Z",
                "updated_at": "2024-05-16T19:30:26Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.1/firmware.bin",
            },
            {
                "url": "https://api.github.com/repos/iot49/leaf/releases/assets/168357553",
                "id": 168357553,
                "node_id": "RA_kwDOL4ZmU84KCO6x",
                "name": "micropython.bin",
                "label": "",
                "uploader": {
                    "login": "github-actions[bot]",
                    "id": 41898282,
                    "node_id": "MDM6Qm90NDE4OTgyODI=",
                    "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/github-actions%5Bbot%5D",
                    "html_url": "https://github.com/apps/github-actions",
                    "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
                    "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
                    "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
                    "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
                    "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
                    "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
                    "type": "Bot",
                    "site_admin": False,
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 1721808,
                "download_count": 0,
                "created_at": "2024-05-16T19:30:26Z",
                "updated_at": "2024-05-16T19:30:26Z",
                "browser_download_url": "https://github.com/iot49/leaf/releases/download/v0.0.1/micropython.bin",
            },
        ],
        "tarball_url": "https://api.github.com/repos/iot49/leaf/tarball/v0.0.1",
        "zipball_url": "https://api.github.com/repos/iot49/leaf/zipball/v0.0.1",
        "body": "**Full Changelog**: https://github.com/iot49/leaf/commits/v0.0.1",
    },
]


class GitReleaseAsset(BaseModel):
    name: str
    size: int
    browser_download_url: Url


class GitRelease(BaseModel):
    tag_name: str
    name: str
    published_at: datetime
    # assets: list[GitReleaseAsset]


class GitReleases(BaseModel):
    releases: list[GitRelease]


@cached(cache=TTLCache(maxsize=32, ttl=600))
async def get_resource(resource: str = "releases"):
    url = f"https://api.github.com/repos/{env.GITHUB_OWNER}/{env.GITHUB_REPO}/{resource}"
    headers = {
        "X-GitHub-Api-Version": "2022-11-28",
        "Accept": "application/vnd.github+json",
    }
    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.get(url) as response:
            if response.status != 200:
                raise HTTPException(status_code=response.status, detail=f"Failed fetching {url}")
            print(response.status)
            return await response.json()


async def get_releases() -> GitReleases:
    # resource = await get_resource("releases")
    resource = RESOURCE
    return GitReleases.model_validate({"releases": resource})


async def get_binary(tag: str = "v0.0.8", board: str = "ESP32_S3_N16R8", file="micropython.bin"):
    url = f"https://github.com/{env.GITHUB_OWNER}/{env.GITHUB_REPO}/releases/download/{tag}/{board}-{file}"
    headers = {
        "X-GitHub-Api-Version": "2022-11-28",
        "Accept": "binary/octet-stream",
    }
    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.get(url) as response:
            if response.status != 200:
                raise HTTPException(status_code=response.status, detail=f"Failed fetching {url}")
            return await response.read()
