name: Compile and release MicroPython firmware

on:
  push:
    tags:
      - '**'

env:
  BOARD: ESP32_S3_N16R8
  IDF_VERSION: v5.0.4

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout required submodules
        working-directory: trees/vm
        run: |
          git submodule update --init micropython
          cd micropython; git submodule update --init lib/berkeley-db-1.xx lib/micropython-lib

      - name: Copy boards to PORT_DIR/boards
        working-directory: trees/vm
        run: |
          echo "TAG = '${{ github.ref_name }}'; BOARD = '${{ env.BOARD }}'; GITHUB_REPOSITORY = '${GITHUB_REPOSITORY}'; IDF_VERSION = '${{ env.IDF_VERSION }}'" > src/freeze/version.py
          cat src/freeze/version.py
          # is there a way for micropython to look for boards in a different directory?
          # until I find out - just copy the files!
          mkdir -p micropython/ports/esp32/boards
          cp -a boards/${{ env.BOARD }} micropython/ports/esp32/boards

      # https://github.com/marketplace/actions/docker-cache
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ env.IDF_VERSION }}

      - name: Compile
        uses: addnab/docker-run-action@v3
        with:
          # https://github.com/espressif/esp-idf/blob/master/tools/docker/Dockerfile
          image: espressif/idf:${{ env.IDF_VERSION }}
          options: -v ${{ github.workspace }}:/project -w /project/trees/vm/micropython -e BOARD=${{ env.BOARD }}
          run: |
            . $IDF_PATH/export.sh
            make -C mpy-cross
            make -C ports/esp32 BOARD=${BOARD} clean
            make -C ports/esp32 V=1 \
                BOARD=${BOARD} \
                USER_C_MODULES=../../../../src/modules/micropython.cmake \
                FROZEN_MANIFEST=../../../../../../src/freeze/manifest.py

            # rename so we can release multiple versions for different boards
            cd ports/esp32/build-${BOARD}
            mv firmware.bin    ${{ env.BOARD }}-firmware.bin
            mv micropython.bin ${{ env.BOARD }}-micropython.bin

      - name: Release
        working-directory: trees/vm/micropython/ports/esp32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="MicroPython VM $tag" \
              build-${{ env.BOARD }}/${{ env.BOARD }}-firmware.bin \
              build-${{ env.BOARD }}/${{ env.BOARD }}-micropython.bin
